const colors = require('tailwindcss/colors')

module.exports = {
  purge: {
    enabled: true,
    content: [
      'src/components/**/*.{js,jsx,ts,tsx}',
      'playground/src/App.tsx',
      'playground/src/examples/**/*.{js,jsx,ts,tsx}',
    ],
  },
  theme: {
    colors: {
      link: 'var(--color-link)',
      'link-hover': 'var(--color-link-hover)',
      transparent: 'transparent',
      current: 'currentColor',
      black: colors.black,
      white: colors.white,
      gray: colors.coolGray,
      success: 'var(--status-success)',
      warning: 'var(--status-warning)',
      danger: 'var(--status-danger)',
      // must match colors in index.css
      color1: {
        50: 'var(--color1-50)',
        100: 'var(--color1-100)',
        200: 'var(--color1-200)',
        300: 'var(--color1-300)',
        400: 'var(--color1-400)',
        500: 'var(--color1-500)',
        600: 'var(--color1-600)',
        700: 'var(--color1-700)',
        800: 'var(--color1-800)',
        900: 'var(--color1-900)'
      },
      color2: {
        50: 'var(--color2-50)',
        100: 'var(--color2-100)',
        200: 'var(--color2-200)',
        300: 'var(--color2-300)',
        400: 'var(--color2-400)',
        500: 'var(--color2-500)',
        600: 'var(--color2-600)',
        700: 'var(--color2-700)',
        800: 'var(--color2-800)',
        900: 'var(--color2-900)'
      },
      color3: {
        50: 'var(--color3-50)',
        100: 'var(--color3-100)',
        200: 'var(--color3-200)',
        300: 'var(--color3-300)',
        400: 'var(--color3-400)',
        500: 'var(--color3-500)',
        600: 'var(--color3-600)',
        700: 'var(--color3-700)',
        800: 'var(--color3-800)',
        900: 'var(--color3-900)'
      },
      color4: {
        50: 'var(--color4-50)',
        100: 'var(--color4-100)',
        200: 'var(--color4-200)',
        300: 'var(--color4-300)',
        400: 'var(--color4-400)',
        500: 'var(--color4-500)',
        600: 'var(--color4-600)',
        700: 'var(--color4-700)',
        800: 'var(--color4-800)',
        900: 'var(--color4-900)'
      },
    },
    fontFamily: {
      sans: [
        'var(--font-sans)',
        'system-ui',
        '-apple-system',
        'BlinkMacSystemFont',
        '"Segoe UI"',
        'Roboto',
        '"Helvetica Neue"',
        'Arial',
        '"Noto Sans"',
        'sans-serif',
        '"Apple Color Emoji"',
        '"Segoe UI Emoji"',
        '"Segoe UI Symbol"',
        '"Noto Color Emoji"',
      ],
      serif: ['var(--font-serif)', 'Georgia', 'Cambria', '"Times New Roman"', 'Times', 'serif'],
      mono: [
        'var(--font-mono)',
        'SFMono-Regular',
        'Menlo',
        'Monaco',
        'Consolas',
        '"Liberation Mono"',
        '"Courier New"',
        'monospace',
      ],
    },
    extend: {
      fill: theme => theme('colors'),
      minHeight: theme => theme('height'),
      maxHeight: theme => theme('height'),
      minWidth: theme => theme('width'),
      maxWidth: theme => theme('width'),
    },
  },
  variants: {
    backgroundColor: ['responsive', 'hover', 'focus', 'group-hover'],
    borderColor: ['responsive', 'hover', 'focus', 'active', 'group-hover'],
    fill: ['responsive', 'hover', 'focus', 'group-hover'],
    padding: ['responsive', 'first'],
    margin: ['responsive', 'first'],
    fontWeight: ['responsive', 'hover', 'focus'],
    textColor: ['responsive', 'hover', 'focus', 'group-hover']
  },
  plugins: [],
}
